GET http://localhost:3333/users/1

###
POST http://localhost:3333/rent-manager/auth/register
Content-Type: application/json

{
  "firstName": "Jean",
  "lastName": "Dupont",
  "email": "jean.dupont@example.com",
  "username": "jeanDuPont",
  "password": "superSecretPassword123",
  "password_confirmation": "superSecretPassword123"
}

### generate a password
POST http://localhost:3333/rent-manager/auth/1/tokens
Content-Type: application/json

### Make a login for user
POST http://localhost:3333/rent-manager/auth/login
Content-Type: application/json

{
  "email":"jean.dupont@example.com",
  "password": "superSecretPassword123"
}