# Generated by Django 6.0.4 on 2026-04-30 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Appartement'), ('HOUSE', 'Maison'), ('STUDIO', 'Studio'), ('OFFICE', 'Bureau'), ('COMMERCIAL', 'Local Commercial'), ('BUILDING', 'Immeuble')], default='APARTMENT', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponible'), ('RENTED', 'Loué'), ('MAINTENANCE', 'En travaux / Maintenance')], default='AVAILABLE', max_length=20)),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('city', models.CharField(default='Abidjan', max_length=100)),
                ('address', models.CharField(default="Rue de l'aménagement", max_length=255)),
                ('price_per_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Loyer mensuel')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Caution')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Nombre de chambres')),
                ('pieces', models.PositiveIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Salles de bain')),
                ('surface_area', models.DecimalField(blank=True, decimal_places=2, help_text='Surface en m²', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire / Gestionnaire')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('title', 'address'), name='unique_title_address')],
            },
        ),
    ]
