# Generated by Django 6.0.3 on 2026-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='La propriété est-elle archivé?'),
        ),
    ]
