# Generated by Django 6.0.4 on 2026-05-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='property_pictures/'),
        ),
    ]
